version: '3'
services:
  daracatum_db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tYAQORgNyV
      MYSQL_DATABASE: daracatum_backend
      MYSQL_USER: daracatum
      MYSQL_PASSWORD: tdAY8zKfkz
    ports:
      - "3306:3306"
  daracatum_app:
    depends_on:
      - daracatum_db
    image: php:7.2-apache
    ports:
      - "80:80"
    restart: always
    environment:
      DB_HOST: daracatum_db:3306
      DB_USER: daracatum
      DB_PASSWORD: tdAY8zKfkz
      APP_ENV: dev
      APP_SECRET: 2e812144275b4979c2ef671ee72f7148
      DATABASE_URL: mysql://db_user:db_password@127.0.0.1:3306/db_name
      MAILER_URL: null://localhost
    volumes:
      - ./app:/var/www
      - ./app/public:/var/www/html
      - ./scripts:/scripts